name: Python Ruff Lint Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Install the latest version of ruff and run ruff check
      uses: astral-sh/ruff-action@v3
      with:
        version: "latest"